### ISSUE TITLE
CP Solver section in the RCPSP-5 Constraint Programming notebook giving a blank outout

### ISSUE THREAD

**Issue by dadleyAD** [airbus/discrete-optimization#350] opened 2024-11-07 12:15 UTC
The [CP Solver section in the RCPSP-5 Constraint Programming.ipynb](https://github.com/airbus/discrete-optimization/blob/master/notebooks/RCPSP%20tutorials/RCPSP-5%20Constraint%20Programming.ipynb) notebook  is not working but simply giving a empty output (`len(results)` is empty) when the following is run. The [Knapsack Constraint Programming section](https://github.com/airbus/discrete-optimization/blob/master/notebooks/Knapsack%20tutorial.ipynb) also suffers from this issue.

```
solver = CpRcpspSolver(problem=rcpsp_problem, cp_solver_name=CpSolverName.CHUFFED)
solver.init_model()
parameters_cp = ParametersCp.default()
results = solver.solve(parameters_cp=parameters_cp, time_limit=20)
```

In addition the following warning is displayed 
`WARNING:discrete_optimization.generic_tools.cp_tools:local variable 'proc' referenced before assignment`

Using latest master branch (394926e59bc40086affc1c700015f92bea7bf043), windows 10, minizinc-python 0.9.0 and minizinc  version 2.8.7 

Likely an error with the minizinc-python bindings or possibly an update in minizinc itself

**Comment by nhuet** [comment] 2024-11-08 14:27
I was not able to reproduce with debian 12, minizinc-python 0.9.0 and minizinc version 2.8.7.
I will try on windows but I have access only to a windows 11 laptop...

**Comment by g-poveda** [comment] 2024-11-29 09:01
This adress the questions, thanks, will close this issue

**Closed by g-poveda** 2024-11-29 09:01 UTC
